name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mkdocs:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    environment:
      name: github-pages
      url: https://jjpaulo2.github.io/converter/

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build the javascript
        run: npm run build

      - name: Prepare files for deployment
        run: |
          mkdir -p site
          cp -R dist site/
          cp index.html site/

      - name: Upload site artifactory
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
